return {
    ["regular"] = {
        ["sunrise"] = {
            [1] = 8,
            [2] = 7,
            [3] = 7,
            [4] = 6,
            [5] = 5,
            [6] = 4,
            [7] = 5,
            [8] = 6,
            [9] = 7,
            [10] = 7,
            [11] = 8,
            [12] = 9,
        },
        ["sunset"] = {
            [1] = 15,
            [2] = 16,
            [3] = 17,
            [4] = 18,
            [5] = 20,
            [6] = 22,
            [7] = 21,
            [8] = 20,
            [9] = 19,
            [10] = 18,
            [11] = 17,
            [12] = 16,
        },
    },
    ["northern"] = {
        ["sunrise"] = {
            [1] = 10,
            [2] = 9,
            [3] = 8,
            [4] = 7,
            [5] = 6,
            [6] = 5,
            [7] = 3,
            [8] = 4,
            [9] = 5,
            [10] = 8,
            [11] = 9,
            [12] = 11,
        },
        ["sunset"] = {
            [1] = 14,
            [2] = 15,
            [3] = 17,
            [4] = 19,
            [5] = 20,
            [6] = 24,
            [7] = 2,
            [8] = 24,
            [9] = 22,
            [10] = 18,
            [11] = 16,
            [12] = 15,
        },
    },
    ["cold regions"] = {
        "Sheogorad Region",
        "Solstheim, Felsaad Coast Region",
        "Solstheim, Moesring Mountains",
        "Solstheim, Isinfier Plains",
        "Solstheim, Hirstaang Forest",
        "Solstheim, Brodir Grove Region",
        "Thirsk Region"
    }
}