return {
    ["open"]={
        ["basket"] = "Fx\\RIGHTRN1.wav",
        ["barrel"] = "Fx\\trans\\drlocked2.wav",
        ["chest"] = "Fx\\chest_opn.wav",
        ["cupboard"] = "Fx\\LEFTRN1.wav",
        ["small chest"] = "Fx\\DOORM1.wav",
        ["crate"] = "Fx\\trans\\drmtl_opn.wav",
        ["sack"] = "Fx\\item\\clothes.wav",
        ["urn"] = "Fx\\trans\\drstn_opn.wav",
        ["desk"] = "Fx\\LEFTRN1.wav",
        ["closet"] = "Fx\\trans\\lrg_gatelatch_lokd.wav",
    },
    ["close"]={
        ["basket"] = "Fx\\RIGHTRN2.wav",
        ["barrel"] = "Fx\\trans\\lrg_gatelatch_lokd.wav",
        ["chest"] = "Fx\\chest_cls.wav",
        ["cupboard"] = "Fx\\LEFTWK1.wav",
        ["small chest"] = "Fx\\DOORW1.wav",
        ["crate"] = "Fx\\trans\\drmtl_cls.wav",
        ["sack"] = "Fx\\item\\clothes.wav",
        ["urn"] = "Fx\\trans\\drstn_cls.wav",
        ["desk"] = "Fx\\LEFTWK1.wav",
        ["closet"] = "Fx\\trans\\drlatch_cls2.wav",
    },
    ["pitch"]={
        ["basket"] = 0.5,
        ["barrel"] = 0.9,
        ["chest"] = 1.0,
        ["cupboard"] = 0.7,
        ["small chest"] = 1.5,
        ["crate"] = 2.5,
        ["sack"] = 0.8,
        ["urn"] = 2.5,
        ["desk"] = 0.5,
        ["closet"] = 0.6,
    },
}
